spring.application.name=cronofatos
spring.datasource.url=jdbc:mysql://localhost:3306/cronofatos
spring.datasource.username=root
spring.datasource.password=974044437
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false